name: flutter_app_getx
description: A new Flutter Getx project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  rxdart: ^0.27.2
  # fluttertoast: ^8.2.1
  intl: ^0.18.1
  # intl_phone_field: ^3.1.0

  # lottie: ^2.5.0
  # carousel_slider: ^4.0.0
  # cached_network_image: ^3.2.3
  # # flutter_statusbarcolor_ns: ^0.4.0
  # pin_code_fields: ^8.0.1
  # flutter_rating_bar: ^4.0.0
  # mask_text_input_formatter: ^2.0.0
  # #loading
  flutter_easyloading: ^3.0.3
  # #html
  # # flutter_html: ^2.2.1
  # #image
  # # image_picker: ^0.8.5+3
  # image_cropper: ^5.0.0
  # #dialog
  # adaptive_dialog: ^1.2.0
  # Network
  retrofit: ^4.0.1
  json_annotation: ^4.3.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0
  retrofit_generator: any

  #local
  shared_preferences: ^2.0.18


dependency_overrides:
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  rxdart: ^0.27.2
  # fluttertoast: ^8.2.1
  intl: ^0.18.1
  intl_phone_field: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/icons/
      - assets/images/
      - assets/animations/
      - assets/json/
      - assets/lang/
