name: flutter_app_getx
description: A new Flutter Getx project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  rxdart: ^0.27.2
  # fluttertoast: ^8.2.1
  intl: ^0.18.1
  # intl_phone_field: ^3.1.0
  http: ^0.13.5
  get_storage: ^2.0.3
  flutter_local_notifications: ^8.2.0
  flutter_easyloading: ^3.0.3
  # google_fonts: ^2.1.0
  # flutter_native_timezone: ^2.0.0
  retrofit: ^4.0.1
  json_annotation: ^4.3.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0
  retrofit_generator: any
  sqflite: ^2.0.0+4
  #local
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.18
  date_picker_timeline: ^1.2.3
  google_fonts: ^4.0.4 

dependency_overrides:
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  rxdart: ^0.27.2
  # fluttertoast: ^8.2.1
  intl: ^0.18.1
  intl_phone_field: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/
      - assets/icons/
      - assets/images/
      - assets/animations/
      - assets/json/
      - assets/lang/
